### ISSUE TITLE
[BUG]: Pushing Client to DP (Server Error)

### ISSUE THREAD

**Issue by JMustardseed** [destevez0610/mustard-app#13]
### Description of the bug

Good morning. Not sure of this is because of the API changes but getting this error message when trying to move client to DP

### Steps to reproduce

Step 1. See video

https://www.loom.com/share/abd67c88046a4164b16d2cb715ce9c9f

### Screenshots

<img width="355" alt="Screen Shot 2023-04-24 at 9 06 20 AM" src="https://user-images.githubusercontent.com/116908122/234007025-16ed73ec-449c-4e7c-b869-831ffbaef3fd.png">

**Comment by markishere16** [comment]
The issue was your dispute panda integration was incorrect. I think you changed your password.
But I already update your DP integration.

Will be fixing the correct error message on this when the DP integration credential is incorrect.

![image](https://user-images.githubusercontent.com/63138664/234008352-5487d4ec-1fb1-4504-8818-11decbbde642.png)
